name: Deploy github-actions-deploy-vue3-to-github-page to GitHub Pages

on:
  push:
    branches: [master]
    paths: ["github-actions-deploy-vue3-to-github-page/**"]   # 仅当 github-actions-deploy-vue3-to-github-page 目录有改动才触发

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: github-actions-deploy-vue3-to-github-page/pnpm-lock.yaml

      - name: Install & Build
        working-directory: github-actions-deploy-vue3-to-github-page          # 进入子目录
        run: |
          pnpm install --frozen-lockfile   # 等价于 npm ci
          pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./github-actions-deploy-vue3-to-github-page/dist             # 产物目录

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4