name: Deploy github-actions-deploy-vue3-to-github-page to GitHub Pages

on:
  push:
    branches: [master]
    paths: ["github-actions-deploy-vue3-to-github-page/**"]   # 仅当 github-actions-deploy-vue3-to-github-page 目录有改动才触发

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1 拉取代码到环境中
      - uses: actions/checkout@v4

      # 2 装 pnpm
      - uses: pnpm/action-setup@v4   # 官方动作，快速装 pnpm
        with:
          version: 10                 # 或锁定你项目里的版本

      # 3 装 Node 并缓存 pnpm store
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: github-actions-deploy-vue3-to-github-page/pnpm-lock.yaml

      # 4 安装 & 构建
      - name: Install & Build
        working-directory: github-actions-deploy-vue3-to-github-page          # 进入子目录
        run: |
          pnpm install --frozen-lockfile   # 等价于 npm ci
          pnpm build

      - name: Debug dist
        run: |
          echo "=== after build ==="
          ls -la ./github-actions-deploy-vue3-to-github-page
          ls -la ./github-actions-deploy-vue3-to-github-page/dist || echo "❌ dist still missing"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./github-actions-deploy-vue3-to-github-page/dist             # 产物目录

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4